### ISSUE TITLE
Errors in log after starting project

### ISSUE THREAD

**Issue by dhowe** [dhowe/GML#1]
![screen shot 2016-11-08 at 6 14 39 am](https://cloud.githubusercontent.com/assets/737638/20078226/a936cfb6-a57a-11e6-9a5b-87c204f3158b.png)

```
Running GenerativeMovementLanguage
[INFO] RiTa.version [1.1.40]
[INFO] Loaded 28084(0) lexicon in 287 ms
Checking /Users/dhowe/Documents/Projects/GML/src/data ...
Found 32 word lists:
Found grammar files:2
rita.RiTaException
<absenceOfSupport.txt>
<attitudeAdverb.txt>
<bodyPartsPlural.txt>
<bodyPartsSingularOfOne.txt>
	at rita.support.RiInvocation.invoke(Unknown Source)
	at com.sun.proxy.$Proxy0.load(Unknown Source)
	at rita.support.YAMLParser.yamlToObject(Unknown Source)
	at rita.support.YAMLParser.yamlToMap(Unknown Source)
	at rita.support.YAMLParser.yamlToJSON(Unknown Source)
	at rita.RiGrammar.load(Unknown Source)
	at rita.RiGrammar.loadFrom(Unknown Source)
	at GenerativeMovementLanguage.setup(GenerativeMovementLanguage.java:128)
	at processing.core.PApplet.handleDraw(PApplet.java:2374)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	... 11 more
Caused by: expected '<document start>', but found FlowMappingStart
 in 'string', line 39, column 1:
    {<phrase1>
    ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	... 15 more
<bodyPartsSingularOfPair.txt>
<chooseLimb.txt>
<degreeAdjective.txt>
<degreeNoun.txt>
<duration.txt>
<endResult.txt>
<flowAdverb.txt>
<gestures.txt>
<lossOfBalance.txt>
<motionAwayFromPerson.txt>
<motionAwayFromSpace.txt>
<motionTowardsPerson.txt>
<motionTowardsSpace.txt>
<movementVerbDirectional.txt>
<movementVerbExtension.txt>
<movementVerbFlexion.txt>
<movementVerbRotation.txt>
<nonMovementVerb.txt>
<otherPerson.txt>
<partsOfTheSpace.txt>
<pathOfBody.txt>
<pathOfLimb.txt>
<preposition.txt>
<props.txt>
<timingAdverb.txt>
<transferenceOfWeight.txt>
<visualShape.txt>
<weightAdjective.txt>
------------------------------
weightAdjective
  'small' [1.0]
  'big' [1.0]
  'delicate' [1.0]
  'strong' [1.0]
  'quick' [1.0]
  'legato' [1.0]
  'rapid' [1.0]
  'pointillist' [1.0]
  'flowing' [1.0]
  'uncertain' [1.0]
  'heavy' [1.0]
  'sharp' [1.0]
  'stacatto' [1.0]
  'random' [1.0]
  'slow' [1.0]
  'light' [1.0]
  'tiny' [1.0]
  'floating' [1.0]
  'restrained' [1.0]
  'huge' [1.0]
  'gentle' [1.0]
  'fragile' [1.0]
timingAdverb
  'against the music' [1.0]
  'with the music' [1.0]
  'in a regular fashion' [1.0]
  'quickly' [1.0]
  'slowly' [1.0]
  'suddenly' [1.0]
  'continuosly' [1.0]
movementVerbDirectional
  'exit' [1.0]
  'move' [1.0]
  'roll' [1.0]
  'run' [1.0]
  'enter' [1.0]
  'stagger' [1.0]
  'approach' [1.0]
  'walk' [1.0]
  'point' [1.0]
  'crawl' [1.0]
bodyPartsSingularOfOne
  'ass' [1.0]
  'chest' [1.0]
  'belly' [1.0]
  'lower back' [1.0]
  'chin' [1.0]
  'upper-body' [1.0]
  'forehead' [1.0]
  'pelvis' [1.0]
  'middle back' [1.0]
  'back' [1.0]
  'spine' [1.0]
  'neck' [1.0]
  'back of the body' [1.0]
  'hip' [1.0]
  'head' [1.0]
  'back of the head' [1.0]
  'face' [1.0]
  'side of the body' [1.0]
  'hair' [1.0]
  'upper back' [1.0]
  'lower-body' [1.0]
  'waist' [1.0]
  'top of the head' [1.0]
  'front of the body' [1.0]
motionAwayFromSpace
  'move' [1.0]
  'avoid' [1.0]
  'reverse' [1.0]
  'push' [1.0]
gestures
  'fall' [1.0]
  'pace' [1.0]
  'bound' [1.0]
  'roll' [1.0]
  'step' [1.0]
  'turn' [1.0]
  'twist' [1.0]
  'jump' [1.0]
duration
  'some time' [1.0]
  'a breath' [1.0]
  'a short time' [1.0]
  'a moment' [1.0]
  'a while' [1.0]
  'a second' [1.0]
  '10 seconds' [1.0]
  'in a loop' [1.0]
  'some seconds' [1.0]
  'as long as possible' [1.0]
chooseLimb
  'left' [1.0]
  'right' [1.0]
degreeAdjective
  '90 degree' [1.0]
  'clockwise' [1.0]
  'anti-clockwise' [1.0]
  '180 degree' [1.0]
  'short' [1.0]
  '360 degree' [1.0]
  '45 degree' [1.0]
  'long' [1.0]
partsOfTheSpace
  'the floor' [1.0]
  'zone 2' [1.0]
  'zone 3' [1.0]
  'the right of the space' [1.0]
  'zone 1' [1.0]
  'the front' [1.0]
  'the front of the space' [1.0]
  'the back' [1.0]
  'the air' [1.0]
  'the left of the space' [1.0]
  'the middle of the space' [1.0]
  'zone 4' [1.0]
  'the back of the space' [1.0]
preposition
  'inside of' [1.0]
  'over' [1.0]
  'behind' [1.0]
  'close to' [1.0]
  'beneath' [1.0]
  'in the middle of' [1.0]
  'down on' [1.0]
  'out of' [1.0]
  'against' [1.0]
  'around' [1.0]
  'onto' [1.0]
  'into' [1.0]
  'toward' [1.0]
  'on top of' [1.0]
  'beside' [1.0]
  'from' [1.0]
  'in opposition to' [1.0]
  'away from' [1.0]
degreeNoun
  '1 meter' [1.0]
  'some meters' [1.0]
  '3 meters' [1.0]
  '2 meters' [1.0]
bodyPartsSingularOfPair
  'finger' [1.0]
  'elbow' [1.0]
  'palm' [1.0]
  'fist' [1.0]
  'wrist' [1.0]
  'leg' [1.0]
  'knee' [1.0]
  'heel' [1.0]
  'shoulder' [1.0]
  'arm' [1.0]
  'ankle' [1.0]
  'foot' [1.0]
  'hand' [1.0]
otherPerson
  'susana' [1.0]
  'partner' [1.0]
  'otherPerson' [1.0]
  'martin' [1.0]
  'isabelle' [1.0]
  'loui-clement' [1.0]
movementVerbRotation
  'rotate' [1.0]
  'spin' [1.0]
  'turn' [1.0]
  'twist' [1.0]
absenceOfSupport
  'swing' [1.0]
  'hang' [1.0]
  'flop' [1.0]
motionTowardsPerson
  'close to' [1.0]
  'face' [1.0]
  'pull towards' [1.0]
  'roll on top of' [1.0]
  'against' [1.0]
props
  'laser' [1.0]
motionTowardsSpace
  'turn to face up' [1.0]
  'move towards' [1.0]
transferenceOfWeight
  'suspend' [1.0]
  'transfer' [1.0]
  'lean' [1.0]
motionAwayFromPerson
  'push away from' [1.0]
  'turn in opposite direction from' [1.0]
  'roll away from' [1.0]
pathOfBody
  'move in spiral' [1.0]
  'walk in diagonal' [1.0]
  'zig-zag' [1.0]
bodyPartsPlural
  'shoulders' [1.0]
  'feet' [1.0]
  'fists' [1.0]
  'thighs' [1.0]
  'hands' [1.0]
  'knees' [1.0]
  'elbows' [1.0]
  'fingers' [1.0]
  'wrists' [1.0]
  'calves' [1.0]
  'hips' [1.0]
  'legs' [1.0]
  'arms' [1.0]
  'ankles' [1.0]
  'palms of the hands' [1.0]
  'toes' [1.0]
movementVerbExtension
  'extend' [1.0]
  'stretch' [1.0]
  'reach' [1.0]
  'lower' [1.0]
  'straighten' [1.0]
  'lift' [1.0]
  'rise' [1.0]
  'open' [1.0]
  'spread' [1.0]
endResult
  'spreading legs wide open' [1.0]
  'placing weight equally between hands and feet' [1.0]
  'until the music changes' [1.0]
visualShape
  'snake arms' [1.0]
attitudeAdverb
  'delicately' [1.0]
  'violently' [1.0]
  'banally' [1.0]
  'passionately' [1.0]
  'sluggishly' [1.0]
  'aggressively' [1.0]
  'neutrally' [1.0]
  'sensually' [1.0]
  'angrily' [1.0]
  'uncontrollably' [1.0]
  'gloriously' [1.0]
  'contentedly' [1.0]
  'as if lost' [1.0]
  'expressively' [1.0]
  'intensely' [1.0]
  'carelessly' [1.0]
  'drunkenly' [1.0]
  'forgetfully' [1.0]
  'musically' [1.0]
  'ecstatically' [1.0]
  'softly' [1.0]
lossOfBalance
  'drop' [1.0]
  'fall' [1.0]
  'collapse' [1.0]
flowAdverb
  'quickly' [1.0]
  'lightly' [1.0]
  'slowly' [1.0]
  'sporadically' [1.0]
  'gradually' [1.0]
  'repetitively' [1.0]
  'regularly' [1.0]
  'smoothly' [1.0]
  'sustainedly' [1.0]
  'tightly' [1.0]
  'randomly' [1.0]
  'freely' [1.0]
  'harmoniously' [1.0]
  'fluidly' [1.0]
nonMovementVerb
  'suspend' [1.0]
  'rest' [1.0]
  'wait' [1.0]
  'relax' [1.0]
  'lie' [1.0]
  'look' [1.0]
  'hold' [1.0]
  'stay' [1.0]
  'halt' [1.0]
  'face' [1.0]
  'freeze' [1.0]
  'slow' [1.0]
  'stop' [1.0]
  'stick' [1.0]
  'stand' [1.0]
  'sit' [1.0]
movementVerbFlexion
  'coil' [1.0]
  'curl' [1.0]
  'curve' [1.0]
  'flex' [1.0]
  'bend' [1.0]
  'contract' [1.0]
  'arch' [1.0]
  'tense' [1.0]
pathOfLimb
  'brush' [1.0]
  'shake' [1.0]
  'throw' [1.0]
  'touch' [1.0]
  'stroke' [1.0]
  'caress' [1.0]
  'rub' [1.0]
------------------------------
OscP5 0.9.6 infos, comments, questions at http://www.sojamo.de/oscP5


### [2016/11/8 6:13:55] PROCESS @ OscP5 stopped.
### [2016/11/8 6:13:55] PROCESS @ UdpClient.openSocket udp socket initialized.
### [2016/11/8 6:13:56] PROCESS @ UdpServer.start() new Unicast DatagramSocket created @ port 8000
### [2016/11/8 6:13:56] PROCESS @ UdpServer.run() UdpServer is running @ 8000
### [2016/11/8 6:13:56] INFO @ OscP5 is running. you (10.0.1.4) are listening @ port 8000
### [2016/11/8 6:13:56] PROCESS @ OscPlug plugging class GenerativeMovementLanguage | addrPattern:/o
sc/response_from typetag:i method:response
### [2016/11/8 6:13:56] PROCESS @ OscPlug plugging class GenerativeMovementLanguage | addrPattern:/o
sc/notify/presets/ironman typetag:i method:presetTotal
### [2016/11/8 6:13:59] PROCESS @ OscP5 stopped.
### [2016/11/8 6:13:59] PROCESS @ UdpServer.run()  socket closed.

```

**Comment by cristianvogel** [comment]
I'm getting a NoSuchMethodError at line 13 grammar.loadFrom("grammarFiles/CristianImprov1.json")

**Comment by cristianvogel** [comment]
ah no sorry I still had the old version of RiTa installed...
